ocaml-multicore/picos

lib/picos/default.ml
test/lib/elements/async_unix.ml
test/lib/foundation/atomic.ml
test/lib/foundation/atomic.mli
test/lib/foundation/thread_atomic.ml
test/lib/foundation/thread_atomic.mli
test/test_server_and_client.ml

This PR:
* Improves the initialization of auxiliary threads such that failure to create thread should not leave program in invalid state.
* Optimizes `Async_unix` examples to attempt operations (`read`, `write`, `accept`) synchronously and then only in case the operation raises `EAGAIN` or `EWOULDBLOCK` is the operation delegated to the IO thread running select.
* Optimizes `Async_unix` to avoids the use of `Atomic`.  The operations are performed within a single domain, so it is possible to just rely on `poll error` to ensure thread switches do not break atomicity.
* Optimizes `Async_unix` to avoid unnecessary wakeups.

Improving the IO example

---

test/lib/schedulers/fifos.ml

Noticed this bug in the example code while discussing the topic with @c-cube.
I suspect this is due to previously using a `select` and pipe based wakeup which is sticky.

Fix to check the wakeup flag before condition wait

---

lib/picos/bootstrap.ml
lib/picos/picos.mli

This PR changes the specification of `Computation.try_attach` to also allow it to return `false` in case the trigger has already been signaled.  The implementation is also changed to check for that.  This allows a scheduler to potentially avoid a bit of work.

Check trigger has not been signaled before attaching to computation

---

lib/picos/effects_intf.ocaml5.ml
lib/picos/picos.ocaml5.ml
test/lib/schedulers/fifos.ml

These help to reduce the overhead of continuing a fiber.

Add `Fiber.continue` and `Fiber.continue_with` helpers

---

lib/picos/domain.ocaml4.ml
lib/picos/picos.mli
test/test_picos.ml

This makes the `DLS` implementation lazy, lock-free, and thread-safe on OCaml 4.
There should really also be a `DLS.compare_and_set: 'a key -> 'a -> 'a -> unit` exposed to allow correct thread-safe lock-free updates, but OCaml 5's `Domain.DLS` does not provide such an operation.
Note that [OCaml 5's `Domain.DLS` is currently not thread-safe](https://github.com/ocaml/ocaml/issues/12677).

Make `DLS` always lazy

---

dune-project
picos.opam
test/dune
test/lib/foundation/mpsc_queue.ml
test/test_mpsc_queue.ml

The parameters to `List.rev_append` were given in the incorrect order.  Fixes #20.

Fix `Mpsc_queue` order

---

dune-project
picos.opam
test/dune
test/lib/traced_atomic/atomic.ml
test/lib/traced_atomic/dune
test/test_picos_dscheck.ml

This adds tests of the `Trigger` and `Computation` concepts using DSCheck.  The implementations of `Trigger` and `Computation` are pretty simple at this point &mdash; almost obviously correct &mdash; but it doesn't hurt to check them.
One thing that came to mind while writing the tests is that it would likely be better to change from `Computation.return` and `Computation.cancel` to `Computation.try_return` and `Computation.try_cancel`.  I'll leave that to a separate PR.

Testing with DSCheck

---

lib/picos/bootstrap.ml
lib/picos/picos.mli
test/lib/elements/promise.ml
test/lib/elements/promise.mli
test/test_picos_dscheck.ml

While the result is often not interesting, there are cases where knowing whether a particular call completed the computation can be useful.

Add `try` versions of `Computation` completion actions

---

lib/picos/bootstrap.ml
test/lib/elements/lazy.ml
test/lib/elements/sync.ml
test/lib/foundation/mpsc_queue.ml

Having the `backoff` last results in smaller code in some cases and keeping the `t` first is helps to keep things more consistent.

Minor refactor to keep `t` as first and `backoff` as last argument

---

bench/bench_current.ml
bench/bench_mpsc_queue.ml
bench/dune
bench/scheduler.ocaml4.ml
bench/scheduler.ocaml5.ml
dune-project
picos.opam
test/dune
test/lib/traced_atomic/dune

This PR upgrades to use [new version of the DSCheck package](https://github.com/ocaml-multicore/dscheck/pull/26) that is available on OCaml 4.  This allows [OCaml-CI](https://github.com/ocurrent/ocaml-ci) to build and run tests on OCaml 4.

Upgrade DSCheck to allow OCaml-CI test on OCaml 4

---

bench/bench_current.ml
lib/picos/bootstrap.ml
lib/picos/default.ml
lib/picos/effects_intf.ocaml4.ml
lib/picos/effects_intf.ocaml5.ml
lib/picos/picos.mli
lib/picos/picos.ocaml5.ml
test/lib/elements/async_unix.ml
test/lib/elements/bundle.ml
test/lib/elements/lazy.ml
test/lib/elements/promise.ml
test/lib/elements/promise.mli
test/lib/elements/sync.ml
test/test_picos.ml

This PR drops the phantom type parameters previously used to document and statically enforce some of the constraints on when and by whom certain operations on `Trigger`s, `Computation`s, and `Fiber`s may be called.  While the phantom types do effectively prevent some mistakes, they have been seen as inconvenient #31.  Instead of using phantom type parameters, the constraints are now briefly documented as warnings (⚠️) in the documentation.

Drop phantom types

---

lib/picos/bootstrap.ml
lib/picos/default.ml
lib/picos/effects_intf.ocaml5.ml
lib/picos/picos.mli
test/lib/schedulers/fifos.ml

This also adds
- `Trigger.from_action` for special uses cases needed by schedulers, and
- `Trigger.dispose` for safer disposal of triggers inside schedulers.

Add some more flesh to the documentation

---

bench/bench_fls_excluding_current.ml
bench/main.ml

This adds a benchmark of `FLS.get` and `FLS.set` operations without including the cost of `Fiber.current ()` (there is a separate benchmark for that).

Add benchmark of `FLS` excluding cost of `Current`

---

lib/picos/picos.mli
test/lib/schedulers/fifos.ml
test/test_picos.ml

The ability to attach a callback to a trigger is the one thing in Picos that must be done with care, because it basically allows you to cause an unknown execution context to call that callback synchronously.  Such callbacks should be written with extreme care.

Add `alert` attributes to dangerous operations

---

lib/picos/intf.ocaml5.ml
lib/picos/picos.mli
lib/picos_fifos/picos_fifos.ml
lib/picos_threaded/picos_threaded.ml

In order to call `Fiber.forbid fiber (fun () -> ...)` to forbid cancelation, it is necessary to call `Fiber.current ()` to obtain the `fiber`.  Hence `Fiber.current ()` must not propagate cancelation.  In some cases one could call `Fiber.current ()` well before performing the work that needs to be protected by `Fiber.forbid ...`, but this is not always practical.

The `Fiber.current ()` operation must never propagate cancelation

---

lib/picos/bootstrap/picos_bootstrap.ml
lib/picos/picos.mli
lib/picos_fifos/picos_fifos.ml
lib/picos_threaded/picos_threaded.ml

I noticed I had failed to account for one case in my previous `await` handler implementations. 😞
This fixes that by introducing a pair of helpers for suspending and unsuspending a fiber. 😌

Add `Fiber.try_suspend` and `Fiber.unsuspend` helpers

---

test/test_sync.ml

With a multithreaded scheduler it was possible for the `Trigger.await` inside the lazy computation to observe the trigger as signaled before performing `Await` where the scheduler would notice that the fiber was canceled.

Avoid race condition in `Lazy` cancelation test

---

lib/picos_select/dune
lib/picos_select/picos_select.ml
lib/picos_select/picos_select.mli
lib/picos_stdio/dune
lib/picos_stdio/picos_stdio.ml
lib/picos_stdio/picos_stdio.mli
test/dune
test/test_select.ml
test/test_server_and_client.ml

This PR
- enhances `Picos_stdio` to handle `EINTR` errors by retrying the computation,
- adds support for "interrupts" into `Picos_select` that generate signals, and
- uses the interrupt support for transparently asynchronous IO with blocking FDs.

Add interrupt support and implement async IO for blocking FDs

---

bench/bench_cancel_after.ml
bench/bench_mutex.ml
bench/bench_spawn.ml
bench/bench_stdio.ml
bench/bench_yield.ml
bench/dune
bench/main.ml
lib/picos_select/dune
lib/picos_select/picos_select.ml
lib/picos_stdio/picos_stdio.ml
test/test_select.ml

This adds a minimal benchmark that tries to measure the overheads that `Picos_select` imposes and fine tunes some of the interrupt handling code a bit for performance &mdash; there is still room to improve.
This PR also enhances the atomicity of the interrupt handling by ensuring that the number of pending interrupts is updated in a linearizable manner.

Add `Picos_stdio` benchmark

---

CHANGES.md
lib/picos_fifos/picos_fifos.ml
lib/picos_fifos/select.none.ml
lib/picos_fifos/select.some.ml
lib/picos_select/picos_select.ml
lib/picos_select/picos_select.mli
lib/picos_stdio/picos_stdio.mli
lib/picos_threaded/picos_threaded.ml
lib/picos_threaded/select.none.ml
lib/picos_threaded/select.some.ml
test/test_select.ml

This PR makes `Picos_select` configurable.  The configurability is really mostly needed by the changes in #91 but moving this into a separate PR hopefully makes the individual changes easier to understand.

Make `Picos_select` explicitly configurable

---

CHANGES.md
lib/picos_select/dune
lib/picos_select/picos_select.ml
lib/picos_select/picos_select.mli
lib/picos_stdio/picos_stdio.ml
lib/picos_stdio/picos_stdio.mli
test/dune
test/test_stdio.ml

This PR adds support for scheduler friendly `Unix.waitpid`, `Unix.wait`, and `Unix.system` on non-Windows platforms.
On Windows I see no way to provide those in a non-blocking fashion (using only the OCaml standard libraries) except by spawning threads and for that a thread pool would make a lot of sense.  So, I'm leaving that for future work.

Support `Unix.wait` and related functions in `Picos_stdio`

---

lib/picos_thread/dune

`thread-local-storage` is needed for correct operation when `threads.posix` exists.  TLS is used to store the fiber identity with `picos.threaded` and that breaks without proper TLS.
I've now run into this a couple of times that I missed `thread-local-storage` from the switch and that unfortunately allowed an invalid build where `threads.posix` (and hence systhreads) existed without `thread-local-storage`.

When `threads.posix` exists we really need `thread-local-storage`

---

lib/picos_select/picos_select.mli
lib/picos_stdio/picos_stdio.mli
test/test_stdio.md

Enable openfile and read test on Win32.  Operations on files are essentially
non-blocking.
Using sockets we can also do non-blocking IO on Windows.

Enable tests on Win32

---

lib/picos_stdio/picos_stdio.ml
lib/picos_stdio/picos_stdio.mli
test/test_stdio.md

This PR adds the missing `Unix.select` on top of `Picos_select`.
This is mostly for completeness sake as I had time to kill on a flight.  I expect having some sort of composable alternatives will give a much nicer interface than `Unix.select`.

Add `Unix.select` to `Picos_stdio`

---

dune-project
lib/index.mld
lib/picos_lwt/dune
lib/picos_lwt/intf.ml
lib/picos_lwt/picos_lwt.ml
lib/picos_lwt/picos_lwt.mli
picos.opam
test/dune
test/test_lwt_unix.ml
test/test_stdio_with_lwt.ml

This PR implements a Picos compatible direct style interface to `Lwt` as a functor, `Picos_lwt.Make (Sleep)`, which is parameterized over an implementation of `sleep`.  This also explores interoperability of `Picos_stdio` with Lwt by ensuring that signal handlng can be configured at application level to work for both.

Picos compatible direct style interface to Lwt

---

bench/scheduler.ocaml4.ml
bench/scheduler.ocaml5.ml
lib/picos/picos.mli
lib/picos_fifos/picos_fifos.ml
lib/picos_fifos/picos_fifos.mli
lib/picos_lwt/intf.ml
lib/picos_lwt/picos_lwt.ml
lib/picos_select/picos_select.mli
lib/picos_stdio/picos_stdio.mli
lib/picos_structured/picos_structured.mli
lib/picos_sync/picos_sync.mli
lib/picos_threaded/picos_threaded.ml
lib/picos_threaded/picos_threaded.mli
test/test_lwt_unix.ml
test/test_scheduler.ocaml4.ml
test/test_scheduler.ocaml5.ml
test/test_select.ml

It still makes sense to require the fiber operations to have it mandatory, because those are not user level operations and should be as fast as possible.

Make the forbid argument optional in sample schedulers

---

lib/picos_lwt/picos_lwt.ml
lib/picos_lwt/picos_lwt.mli
test/test_lwt_unix.ml

I realized there is no need to use a functor.  `await` could be just moved outside of the functor and `sleep` is a monomorphic function, which can easily be passed around - a functor is overkill.

Defunctorize `Picos_lwt`

---

lib/picos_structured/picos_structured.mli
lib/picos_structured/run.ml
test/test_structured.ml

There are a number of reasons for making this change.
While it sort of makes logical sense to block on an empty list, that can also be surprising and undesirable.  This has also come up as an opinion in private communications.
For example, suppose you want to use `Run.any` to start actions to try to search for a solution concurrently and the list of actions to use in the search is dynamically created.  A simple program such as
```ocaml
let solution = Atomic.make None in
...
Run.any search_actions;
match Atomic.get solution with
| None -> ...
| Some solution -> ...
```
might unexpectedly block in case the list of actions would be empty.
The above also illustrates that it is typically not difficult to implement the blocking semantics on top of the non-blocking semantics (i.e. just block in …

Change `Picos_structured.Run.any []` to not block

---

lib/picos_structured/bundle.ml
lib/picos_structured/picos_structured.mli
lib/picos_structured/run.ml

This changes the implementation of `Run.any` and `Run.all` to only use the single computation of the bundle used internally.

Optimize `Run` module operations

---

lib/index.mld
lib/picos/intf.ocaml5.ml
lib/picos/picos.mli
lib/picos_structured/bundle.ml
lib/picos_threaded/picos_threaded.ml

This PR "tightens" the wordings on the requirements for schedulers when implementing the Picos effects.
The words "must" and "should" are now used more intentionally.
The biggest change is that the `Spawn` effect should now be all or nothing &mdash; if `spawn` returns normally, the scheduler should guarantee that all the mains spawned will be called and if `spawn` raises no mains should be called.  This is how the sample effects based schedulers have worked already (modulo running out of memory) and this requirement has crossed my mind earlier, but for some reason I had failed to spell it out explicitly.   This PR also changes `Picos_threaded` to provide the same guarantee as much as possible.  The reason behind this is that otherwise it becomes very tricky (impossible even) to ensure …

Elaborate on contracts

---

lib/picos_randos/dune
lib/picos_randos/picos_randos.ml
lib/picos_randos/picos_randos.mli
test/dune
test/test_picos.ml
test/test_scheduler.ocaml4.ml
test/test_scheduler.ocaml5.ml
test/test_schedulers.ml
test/test_server_and_client.ml
test/test_stdio.ml
test/test_structured.ml
test/test_sync.ml

This PR adds a low level interface to `Picos_randos` to allow it to use multiple threads and/or domains.

Support multi-threaded use in `Picos_randos`

---

lib/picos_htbl/atomic.ml
lib/picos_htbl/picos_htbl.ml

The `include` construct at the module level is quite expensive in terms of generated code size.

Avoid cost of `include`

---

dune-project
lib/picos_htbl/picos_htbl.ml
picos.opam

See [PR in multicore-magic](https://github.com/ocaml-multicore/multicore-magic/pull/13).
This seems to improve performance in cases of low contention and potentially degrades performance in cases of high contention, which is natural, because an unboxed atomic array uses less words of memory, which makes false sharing more likely.  The performance of this kind of table is naturally relatively worse in cases of low contention (when e.g. compared to lock based techniques), so it makes sense to implement optimizations that improve relative performance in cases of low contention.
I experimented briefly with scaling the capacity based on the number of domains accessing the table in parallel.  However, the results of that were not conclusive, i.e. it is unclear whether there was a performance …

Implement `Picos_htbl` using `Atomic_array`

---

.github/workflows/workflow.yml
bench/bench_binaries.ml
lib/index.mld
lib/picos_lwt/dune
lib/picos_lwt/intf.ml
lib/picos_lwt/picos_lwt.ml
lib/picos_lwt/picos_lwt.mli
lib/picos_lwt_unix/dune
lib/picos_lwt_unix/picos_lwt_unix.ml
lib/picos_lwt_unix/picos_lwt_unix.mli
lib/picos_randos/picos_randos.ml
lib/picos_select/picos_select.ml
lib/picos_select/picos_select.mli
lib/picos_thread/picos_thread.posix.ml
test/dune
test/test_lwt_unix.ml
test/test_scheduler.ocaml4.ml
test/test_scheduler.ocaml5.ml
test/test_stdio_with_lwt.ml

The `System` module is then used to give both a `sleep` function and a kind of trigger mechanism.  The trigger mechanism is needed to be able to safely wake up Lwt in a multi threaded and/or multi domain program.  I think it could actually be a good idea to add more multicore OCaml to Lwt to allow some way to safely interact with Lwt from any systhread on any domain.
This PR also tweaks the way the `Test_scheduler` does things and sets up signal handling in a way that it can work with both `Picos_stdio.Unix` and `Lwt_unix`.  However, the approach done to setup signal handling is a bit of hack, IMHO.  It does seem to work, but this should probably be revisited at some point.  Ideally there would be some library that allows other libraries to setup signal handlers more cooperatively.  The …

Change `Picos_lwt` to take `module System` as argument

---

lib/picos/picos.mli
lib/picos_select/dune
lib/picos_select/picos_select.ml
lib/picos_select/picos_select.mli
lib/picos_sync/event.ml
lib/picos_sync/picos_sync.ml
lib/picos_sync/picos_sync.mli

This PR adds an `Event` module providing a subset of the functionality of the [`Event`](https://ocaml.org/manual/5.2/api/Event.html) module provided by the POSIX threads library that is distributed with OCaml.
The basic idea for this arise out of discussions with @c-cube.  We realized that the `Computation` concept provided by the Picos core interface is quite close to providing everything necessary to implement Concurrent ML style events.
The main feature missing to provide full Concurrent ML style events would be the ability to atomically complete two computations.  It is possible to implement such an operation (I know several techniques that would work), but that is left for future work.  Another feature missing is `wrap_abort` and/or `with_nack`.  It should also be possible to …

Add `Event` abstraction to `Picos_sync`

---

lib/picos_structured/dune
lib/picos_structured/picos_structured.mli
lib/picos_structured/promise.ml
lib/picos_sync/event.ml
lib/picos_sync/picos_sync.mli
test/test_structured.ml
test/test_sync.ml

This PR adds `Event.from_computation` and uses that to provide `Promise.completed`.  This allows e.g. waiting for one of many promises to complete, i.e. racing promises.

Add ability to view completion of a `Computation` as an `Event`

---

lib/picos_structured/picos_structured.mli
lib/picos_sync/latch.ml
lib/picos_sync/picos_sync.ml
lib/picos_sync/picos_sync.mli

This PR adds a `Latch` mechanism to `Picos_sync` and adds an example demonstrating that `Bundle` collects all of the errors from fibers forked into the bundle.

Show that `Bundle` collects all errors and add a `Latch` mechanism

---

bench.Dockerfile
dune-project
picos.opam

This exposes variation due to effects that individual benchmarks have on the runtime state.

Use multicore-bench with suite order randomization

---

lib/picos_lwt_unix/picos_lwt_unix.ml

Previously I had rolled my own version of a notification mechanism as I didn't know one already existed in `Lwt_unix`.  This PR changes `Picos_lwt_unix` to use the existing mechanism provided by `Lwt_unix`.

Change to use the `Lwt_unix` notification mechanism

---

bench.Dockerfile
lib/picos_randos/picos_randos.ml

The code for spawning fibers was probably copied from `Picos_fifos` and was also correct before enhancing `Picos_randos` to support running on multiple cores. With multiple runners the count must be updated before pushing new `Spawn`s into the collection, because otherwise the count may incorrectly become `0` too early.

Fix `Picos_randos` to count alive fibers correctly

---

bench/bench_cancel_after.ml
bench/bench_computation.ml
bench/bench_current.ml
bench/bench_dls.ml
bench/bench_fls_excluding_current.ml
bench/bench_htbl.ml
bench/bench_mpscq.ml
bench/bench_mutex.ml
bench/bench_tls.ml
bench/countdown.ml
bench/countdown.mli

This should reduce contention in benchmarks and potentially give more precise and accurate results.

Use scalable `Countdown` in benchmarks

---

lib/picos_structured/finally.ml

This allows a decent optimizing compiler to eliminate the tuple allocation.
Unfortunately, at the time of writing, `ocamlopt` is not such an optimizing compiler, but Flambda seems to be able to do it.

Allow `let@` to be inlined

---

lib/picos_sync/picos_sync.mli
test/test_structured.ml

Using `Condition.signal` is not correct in these cases, because it is possible that multiple fibers manage to start `Condition.wait` and a single `Condition.signal` does not wake up all of them.  Another alternative would be to `Condition.signal` every time the queue is not empty or is not full.

Fix bounded queue example to use `Condition.broadcast`

---

lib/picos_structured/bundle.ml
lib/picos_structured/control.ml
lib/picos_structured/picos_structured.mli
lib/picos_structured/promise.ml
test/test_structured.ml

This PR adds `Control.terminate_after ~seconds thunk` to run the given thunk with a timeout on the current fiber and `Bundle.terminate_after ~seconds bundle` to similarly terminate a bundle.

Add `Control.terminate_after` and `Bundle.terminate_after`

---

lib/picos_structured/bundle.ml
lib/picos_structured/control.ml

During a poll point the OCaml runtime may e.g. handle Ctrl-C (i.e. SIGINT) and raise an asynchronous exception that could cause leaks.

Try to avoid poll in `Control.terminate_after` between critical ops

---

lib/picos_structured/picos_structured.mli
lib/picos_sync/ivar.ml
lib/picos_sync/picos_sync.ml
lib/picos_sync/picos_sync.mli

An `Ivar` can be implemented trivially using a `Computation`.
This PR also adds an example of how one can move resources between threads using the resource management helpers provided by the `Picos_structured.Finally` module.

Add incremental or single-assignment poisonable variable

---

bench/bench_stream.ml
bench/main.ml
lib/picos_sync/picos_sync.ml
lib/picos_sync/picos_sync.mli
lib/picos_sync/stream.ml

This PR adds a many-to-many, poisonable (i.e. closable) stream to the `Picos_sync`.  This is inspired by the [`Multicast` channel](http://cml.cs.uchicago.edu/pages/multicast.html) provided by Concurrent ML and can be useful for a variety of purposes.

Add a many-to-many, poisonable stream

---

lib/picos_finally/picos_finally.ml
lib/picos_finally/picos_finally.mli
lib/picos_structured/picos_structured.mli
test/test_finally.ml
test/test_server_and_client.ml

This changes `Picos_finally` to use `let (let@) = (@@)` as the only binding operator.
Thanks to @c-cube and @edwintorok for discussion on this topic!

Redesign resource management to use only one binding operator

---

bench/bench_bounded_q.ml
bench/bench_cancel_after.ml
bench/bench_mutex.ml
bench/bench_yield.ml
lib/picos/picos.mli
lib/picos_finally/picos_finally.mli
lib/picos_select/picos_select.mli
lib/picos_stdio/picos_stdio.mli
lib/picos_structured/bundle.ml
lib/picos_structured/flock.ml
lib/picos_structured/picos_structured.ml
lib/picos_structured/picos_structured.mli
lib/picos_structured/run.ml
lib/picos_sync/picos_sync.mli
test/test_lwt_unix.ml
test/test_picos_lwt_unix_with_cohttp.ml
test/test_schedulers.ml
test/test_select.ml
test/test_server_and_client.ml
test/test_stdio.ml
test/test_structured.ml
test/test_sync.ml

This PR adds to the `picos.structured` library a new `Flock` module, which essentially provides a more convenient interface to the existing `Bundle` mechanism by passing the underlying `Bundle` through `FLS`.
The naming is a bit tongue in cheek.  The idea is that, unlike a "[bundle](https://www.merriam-webster.com/dictionary/bundle)", a "[flock](https://www.merriam-webster.com/dictionary/flock)" (like a flock of birds) is something that you cannot really hold in your hands.   Flock is also a term used in conjuction with fibers.

Add an implicitly propagated flock of fibers

---

lib/picos/picos.common.ml
lib/picos/picos.mli
lib/picos_fifos/picos_fifos.ml
lib/picos_fifos/picos_fifos.mli

Previously `picos.fifos` used to allocate effect handling functions per fiber.  This PR changes those allocations to be done only once, which reduces per fiber memory usage signficantly.
This also adds an optional `quota` for the number of effects a fiber is allowed to perform before being forced to yield.

Reduce per fiber allocations in `picos.fifos`

---

lib/picos_structured/bundle.ml
lib/picos_structured/flock.ml

Per fiber computation is only needed when a fiber is forked as a (separately) cancelable promise.

Optimize `Bundle.fork` to not use per fiber computation

---

bench/scheduler.ocaml5.ml
lib/picos_fifos/picos_fifos.ml

This fixes `Picos_fifos` to actually update the remaining `quota` after performing an effect successfully and also changes the benchmark scheduler to specify `~quota:100`.

Fix to actually update the quota

---

bench/bench_fib.ocaml5.ml
bench/bench_memory.ml
bench/bench_spawn.ml
lib/picos/bootstrap/picos_bootstrap.ml
lib/picos/intf.ocaml5.ml
lib/picos/ocaml4/picos_ocaml.ml
lib/picos/ocaml5/picos_ocaml.ml
lib/picos/picos.mli
lib/picos_fifos/picos_fifos.ml
lib/picos_fifos/picos_fifos.mli
lib/picos_lwt/picos_lwt.ml
lib/picos_lwt/picos_lwt.mli
lib/picos_lwt_unix/picos_lwt_unix.ml
lib/picos_lwt_unix/picos_lwt_unix.mli
lib/picos_randos/picos_randos.ml
lib/picos_randos/picos_randos.mli
lib/picos_structured/bundle.ml
lib/picos_structured/run.ml
lib/picos_threaded/picos_threaded.ml
lib/picos_threaded/picos_threaded.mli
test/test_picos.ml
test/test_scheduler.ocaml4.ml
test/test_scheduler.ocaml5.ml
test/test_schedulers.ml
test/test_structured.ml
test/test_sync.ml

This PR essentially redesigns the `Fiber.spawn` mechanism to allow `FLS` to be populated before a fiber is spawned. Being able to populate the `FLS` before spawn can be used to reduce the amount of allocations required (i.e. this results in smaller `main` closure for the fiber) and also allows some use cases to be implemented more easily.
This also removes the early idea of giving a list of `main` functions, which allowed multiple fibers to be spawned with a single effect.  It seems that moving the allocation of the fiber record to happen before `spawn` also speeds up a single spawn.  This is nice, because, in most cases, one spawns one fiber at a time.
This also introduces the concept of _fatal errors_.  Previously, if the `main` function of a fiber raised an exception, it was considered …

Redesign `Spawn` and introduce concept of fatal errors

---

lib/picos_randos/dune
lib/picos_randos/picos_randos.ml

This allows the effect handlers to be preallocated once and the space taken by a fiber reduced significantly.

Use TLS to store current fiber in `picos.randos`

---

bench/bench_binaries.ml
lib/index.mld
lib/picos_mpmcq/dune
lib/picos_mpmcq/picos_mpmcq.ml
lib/picos_mpmcq/picos_mpmcq.mli
lib/picos_mpscq/picos_mpscq.mli
test/dune
test/test_mpmcq.ml

This adds a MPMC queue with the ability to push to both ends of the queue, which makes it possible to prioritize cancelation.
This should already give pretty good performance when mostly used from one domain.
The `push_head` operation can be optimized further (I did a quick attempt and got up to 15% improvement in a high contention benchmark) and there are probably some more tweaks that could improve performance a bit, but I'm leaving that to future work.

Add multi-producer multi-consumer queue allowing pushes to both ends

---

README.md
dune-project
lib/index.mld
lib/picos_select/picos_select.ml
lib/picos_select/picos_select.mli
lib/picos_stdio_cohttp/dune
lib/picos_stdio_cohttp/picos_stdio_cohttp.ml
lib/picos_stdio_cohttp/picos_stdio_cohttp.mli
picos.opam
test/dune
test/test_stdio_cohttp.ml

This PR adds minimalistic Cohttp `Client` and `Server` modules using `picos.stdio` for IO.
This also changes `Picos_select` to configure `SIGPIPE` to be ignored by default.  This makes it easier to deal with cases where one end of a communication is closed before the other end is done.
This is definitely not a final solution, but I need a minimalistic HTTP client and don't have time to think through how to support more interesting use cases in the best way with Cohttp.  Testing is also not very thorough at this point.  In other words, improvements, including highly likely breaking changes, are left for future work.
Feedback from potential users is welcome!

Add minimalist Cohttp implementation using `Picos_stdio`

---

lib/picos_stdio_cohttp/picos_stdio_cohttp.ml

Another bug found via randomization, see #225.

Fix off-by-one error in `read_line`

---

lib/picos_sync/condition.ml
lib/picos_sync/mutex.ml

It is not entirely obvious whether or not this improves performance, but after spending some time looking through the benchmark results, it seems plausible that this does improve performance.

Avoid entry reallocation

---

lib/picos_threaded/picos_threaded.ml

This seems to have been introduced in PR #210 and is not how spawn is specified to behave.

Fix to not cancel computation In case of spawn failure

---

bench/bench_semaphore.ml
bench/main.ml
lib/picos_structured/picos_structured.mli
lib/picos_sync/condition.ml
lib/picos_sync/mutex.ml
lib/picos_sync/picos_sync.ml
lib/picos_sync/picos_sync.mli
lib/picos_sync/q.ml
lib/picos_sync/semaphore.ml
test/test_structured.ml
test/test_sync.ml

This PR adds a [Stdlib style `Semaphore` module](https://ocaml.org/manual/5.2/api/Semaphore.html) to the `Picos_sync` library.  The implementation is mainly optimized for size and simplicity in certain respects.  The implementation is not optimized for cancelation.  This also introduces an internal queue `Q` module that is then used also in `Mutex` and `Condition`.

Add `Stdlib` style `Semaphore` module to `Picos_sync`

---

bench/dune
test/dune

The mutex & condition cancelation test and some benchmark(s) occasionally hang.  This changes the `picos.sync` tests and the benchmarks to be run one-by-one so that the problematic cases can be isolated.

Which test or benchmark occasionally hangs?

---

bench/bench_bounded_q.ml
bench/bench_memory.ml
bench/bench_semaphore.ml
lib/picos_select/picos_select.mli
lib/picos_stdio/picos_stdio.mli
lib/picos_stdio_cohttp/picos_stdio_cohttp.mli
lib/picos_structured/bundle.ml
lib/picos_structured/flock.ml
lib/picos_structured/picos_structured.mli
lib/picos_sync/picos_sync.mli
test/test_server_and_client.ml
test/test_stdio.ml
test/test_stdio_cohttp.ml
test/test_structured.ml

Having a `Bundle` or `Flock` terminate fibers on return is often convenient. In particular, this is convenient for setting up a bundle for daemon fibers:
```ocaml
Bundle.join_after ~on_return:`Terminate @@ fun daemons ->
Bundle.fork daemons (fun () -> (* ... *))
(* ... *)
```
Another alternative (one of many) is to fork as a promise and use a finalizer:
```ocaml
let@ _daemon =
finally Promise.terminate @@ fun () ->
Flock.fork_as_promise @@ fun () ->
(* ... *)
in
(* ... *)
```

Add optional argument to terminate `Bundle` and `Flock` on return

---

lib/picos_mpmcq/picos_mpmcq.ml
lib/picos_mpmcq/picos_mpmcq.mli
test/test_mpmcq.ml

The tweaks clearly improved performance on my Apple M3 Max laptop, but improvements on the AMD Zen 1 and Opteron benchmarking servers are unclear.
```
➜  picos-this git:(add-length-to-queue-and-tweaks) ✗ dune exec --release -- ./bench/main.exe -budget 2 -diff bench-mpmcq-hi.json
Picos_mpmcq:                          
time per message/one domain:
16.20 ns = 1.00 x 16.25 ns
messages over time/one domain:
61.72 M/s = 1.00 x 61.54 M/s
time per message/1 nb adder, 1 nb taker:
15.27 ns = 0.82 x 18.70 ns
messages over time/1 nb adder, 1 nb taker:
130.95 M/s = 1.22 x 106.94 M/s
time per message/1 nb adder, 2 nb takers:
28.30 ns = 0.91 x 31.09 ns
messages over time/1 nb adder, 2 nb takers:
106.02 M/s = 1.10 x 96.49 M/s
time per message/2 nb adders, 1 nb taker:
31.32 ns = 0.92 x 34.14 ns …
```

Add `Picos_mpmcq.length` and tweak for performance

---

lib/picos/bootstrap/picos_bootstrap.ml
lib/picos/ocaml5/picos_ocaml.ml
lib/picos/picos.mli
lib/picos_exn_bt/picos_exn_bt.ocaml4.ml
lib/picos_exn_bt/picos_exn_bt.ocaml5.ml

`peek` is often used in the fast path of some operations, so
ideally it should not allocate.

add `Picos.Computation.peek_exn`

---

test/stm_run/intf.ml
test/stm_run/stm_run.ocaml4.ml
test/stm_run/stm_run.ocaml5.ml

This is now possible, because the tests are being run with a time based budget and that prevents tests from taking way too long on slower targets.

Use same STM test count and time budgets on all targets

---

test/dune
test/test_schedulers.ml

Working to port Kcas to Picos I noticed some (I believe) lost wakeups causing benchmarks to never finish.  This test exercises a similar scenario, running schedulers on two domains.  This doesn't seem to reproduce the issue however.  The mutex and condition cancelation test also works on all the schedulers (at least on macOS).

Test cross scheduler wakeup

---

lib/picos_io.select/picos_io_select.ml
lib/picos_lwt.unix/picos_lwt_unix.ml
test/test_io_with_lwt.ml
test/test_scheduler.ocaml4.ml
test/test_scheduler.ocaml5.ml
test/test_sync.ml

Also do not configure select during module level initialization in the test scheduler.

Raise proper error when select has not been configured

---

lib/picos_io/picos_io.ml

`Unix.socketpair` occasionally fails on Windows:
```diff
--- a/_build/default/lib/picos_io/picos_io.mli
+++ b/_build/default/lib/picos_io/.mdx/picos_io.mli.corrected
@@ -753,7 +753,5 @@ end
send_string "Hello, world!";
send_string "POSIX with OCaml";
end
-      Hello, world!
-      POSIX with OCaml
-      - : unit = ()
+      Exception: Unix.Unix_error(Unix.EADDRINUSE, "socketpair", "")
]} *)
```
This introduces a workaround to retry `Unix.socketpair` a few times to avoid random CI failures #259.

Attempt to work around `Unix.socketpair` issue on Win32

---

lib/picos_io.select/picos_io_select.ml
lib/picos_io/picos_io.ml
lib/picos_lwt.unix/picos_lwt_unix.ml
lib/picos_lwt/picos_lwt.ml
lib/picos_mux.fifo/picos_mux_fifo.ml
lib/picos_mux.multififo/picos_mux_multififo.ml
lib/picos_mux.random/picos_mux_random.ml
lib/picos_mux.thread/picos_mux_thread.ml
lib/picos_std.event/event.ml
lib/picos_std.sync/ivar.ml
lib/picos_std.sync/stream.ml

The new `Computation.peek_exn` should be preferred over `Computation.await` in cases where the computation is supposed to be completed already.

Use the new `Computation.peek_exn` when computation is completed

---

lib/picos_std.finally/picos_std_finally.ml
lib/picos_std.finally/picos_std_finally.mli

I was previously undecided on whether it should be done implicitly, but it has turned out to be surprising, so, now I'm convinced that the right thing to do is to forbid cancelation propagation during resource `release` calls.
The issue is that if a fiber gets canceled, then resource `release` operations that might need to await for something asynchronous may not be properly run to completion.  This can be surprising and, also, because this only happens in cases of cancelation, which could happen at any moment, could be a major source of subtle bugs.
The downside of forbidding cancelation is that in some cases a `release` operation might block indefinitely and this can also cause issues.  However, I believe those cases will be both harder to miss (your program hangs rather than leaks) and …

Forbid cancelation propagation during `release`

---

lib/picos_lwt.unix/picos_lwt_unix.ml
lib/picos_lwt.unix/picos_lwt_unix.mli

This is convenient for use with MDX, which does some magic when you refer to `Lwt`, which can break things.

Add `run_main`

---

CHANGES.md
lib/picos_std.sync/ivar.ml
lib/picos_std.sync/picos_std_sync.mli
lib/picos_std.sync/stream.ml

This should make `poison`able data structures more convenient to use.

Change `poison` to `poison_at` and add `poison` with `?callstack`

---

lib/picos_std.finally/picos_std_finally.ml
lib/picos_std.finally/picos_std_finally.mli

The problem with `Fun.protect` is that it doesn't forbid cancelation propagation.

Add `lastly` as a safer alternative to `Fun.protect`

---

lib/picos_io/picos_io.ml

This is yet another error that `Unix.socketpair` may raise on Windows, see #259.

Also retry `socketpair` on `ENOENT` on Windows

---

lib/picos_std.sync/picos_std_sync.mli
test/dune
test/test_sync.ml

This can help to simplify and optimize code in some cases as these operations are often used in finalizers.

Note and test that certain operations are not cancelable

---

lib/picos/computation.bootstrap.ml
lib/picos/fiber.bootstrap.ml
lib/picos/trigger.bootstrap.ml
lib/picos_std.sync/semaphore.ml

It seems the native OCaml compiler generates suboptimal code when one uses the `||` or the `&&` operators.

Tweak conditionals with CAS

---

update-gh-pages-for-tag

I noticed I had updated docs without `sherlodoc`, which results in not having the nice search bar with the docs.  This should prevent that from happening again.

Make sure `sherlodoc` is installed when updating docs

---

lib/picos_aux.htbl/picos_aux_htbl.ml
lib/picos_aux.htbl/picos_aux_htbl.mli
test/test_htbl.ml

This PR adds some missing and useful operations to the hash table that are designed to work as building blocks of non-blocking algorithms.  Specifically, the operation signatures and semantics are designed to allow building [consensus protocols over arbitrary numbers of processes](https://dl.acm.org/doi/10.1145/62546.62593).

Add missing and useful ops to hash table

---

bench/bench_binaries.ml
bench/dune
lib/picos_std.awaitable/dune
lib/picos_std.awaitable/picos_std_awaitable.ml
lib/picos_std.awaitable/picos_std_awaitable.mli
lib/picos_std/index.mld

This PR adds a futex-like awaitable atomic location abstraction.  This can be useful for implementing various kinds of synchronization and communication primitives.  For example, it can be used to implement mutexes and condition variables with good performance.  Below shows the speed up obtained by replacing the fair mutex and condition with unfair mutex and condition implemented using the awaitable abstraction:

Add `Awaitable` atomic locations

---

lib/picos_std.awaitable/dune
lib/picos_std.awaitable/picos_std_awaitable.ml
lib/picos_std.awaitable/picos_std_awaitable.mli

The use of `Trigger` is exposed to allow awaiting for multiple things.
The internal cleanup is made more robust to make sure awaitables will not be leaked.

Refine the `Awaitable` abstraction

---

lib/picos.thread/thread.ocaml4.js

Don't refer to `caml_ml_domain_id` on OCaml 4

---

test/dune

`js_of_ocaml` 5.9.0 started using `node:` prefixed modules, which do not exist on old node versions.

Work around breaking change in `js_of_ocaml` 5.9.0

---

bench/bench_hashtbl.ml
bench/bench_lock_yield.ml
bench/bench_ref.ml
lib/picos_std.sync/picos_std_sync.ml
lib/picos_std.sync/picos_std_sync.mli
lib/picos_std.sync/rwlock.ml
test/dune
test/test_rwlock.ml
test/test_sync.ml

This PR adds a low overhead `Rwlock`, with an associated `Condition` variable, using the `Awaitable` abstraction.
For future work:
- Experiment with alternatives to prevent writer starvation.  The simple approach of just immediately making readers wait when there is a writer waiting decreases performance.

Add `Rwlock`

---

lib/picos_std.sync/barrier.ml
lib/picos_std.sync/picos_std_sync.ml
lib/picos_std.sync/picos_std_sync.mli
test/dune
test/test_sync.ml

This PR adds a slim poisonable barrier to `picos_std.sync` &mdash; the barrier state and configuration is stored in a single `int Awaitable.t`.  The state of the barrier is mostly updated using `fetch_and_add`, which should perform well.
In the future the bit manipulation logic could probably be tweaked or the OCaml compiler improved save a few instructions.  The potential performance improvement from that is likely to be tiny, however.

Add a poisonable `Barrier` to `picos_std.sync`

---

lib/picos_aux.mpmcq/picos_aux_mpmcq.ml
lib/picos_mux.multififo/picos_mux_multififo.ml
lib/picos_mux.multififo/picos_mux_multififo.mli

This PR implements a simple strategy to balance the amount of fibers running per thread in the multififo scheduler.  This improves the fairness of the multififo scheduler.  Each worker has a countdown to become a thief.  As a thief, they then pick a random victim.  If the victim has more ready fibers, then an attempt is made to steal from the queue of the victim.  The countdown is reset based on the number of fibers in the ready queue.

Make multififo threads periodically steal to balance load

---

lib/picos_std.structured/bundle.ml

This reduces the size of a bundle by inlining the atomic to the bundle record.

Tweak bundle representation

---

lib/picos/picos.mli
lib/picos/picos.ocaml5.ml
lib/picos_std.structured/bundle.ml

This slightly reduces memory usage of a bundle until the trigger is actually needed, which might be never.

Allocate the trigger for a bundle lazily

---

lib/picos_mux.multififo/dune
lib/picos_mux.multififo/picos_mux_multififo.ml
lib/picos_mux.multififo/picos_mux_multififo.mli

This changes the multififo scheduler to wakeup runners only on periodic heartbeats.  This avoids the thundering herd problem.  A separate heartbeat thread is used to maintain the property that if there are `n` ready fibers that never yield and terminate (only) if run in parallel, and the scheduler runs with `n` (or more domains), then such a program will terminate, i.e. that the `n` fibers will eventually run on `n` different domains.

Use heartbeats to wake up runners in multififo

---

bench/bench_bounded_q.ml
bench/bench_mpmcq.ml
bench/bench_mpscq.ml
bench/bench_stream.ml

Queues were previously benchmarked with immediate values only, which unfortunately partially hides the potential cost of write barriers related to setting and clearing elements.

Bench queues with heap allocated blocks

---

bench/dune
bench/scheduler.ocaml5.ml

For practical reasons, benchmark primarily with the multififo scheduler.

More benchmarks with the multififo scheduler
