ocaml-multicore/picos

test/lib/foundation/mpsc_queue.ml
=> Seems better to just `exchange` directly

lib/picos/picos.mli
This PR adds overview documentation on the default bahviours.
=> Document defaults in general

test/lib/elements/promise.ml, test/lib/elements/promise.mli
We should have (more) proper tests for these examples, but I'm going to leave that to future for now.
=> Add an example of how to await for one of any number of computations

lib/picos/bootstrap.ml, lib/picos/picos.mli, test/lib/elements/promise.ml, test/lib/elements/sleep.ml, test/test_picos.ml, test/test_picos_dscheck.ml
The order has an effect on scheduling so it makes to allow it to be specified.
=> Allow to specify order in which triggers are signaled on completion

lib/picos_select/picos_select.ml
This avoids an allocation and some atomics.
=> Use `with_action`

lib/picos_select/dune, lib/picos_select/picos_select.mli, lib/picos_stdio/picos_stdio.mli
Some more MDX checked examples.
=> Some more examples

lib/picos/dune, lib/picos/picos.mli, lib/picos_select/dune, lib/picos_select/picos_select.mli, lib/picos_stdio/dune, lib/picos_stdio/picos_stdio.ml, lib/picos_stdio/picos_stdio.mli, test/dune, test/test_htbl.md, test/test_picos.ml, test/test_scheduler.ocaml4.ml, test/test_scheduler.ocaml5.ml, test/test_schedulers.md, test/test_select.ml, test/test_stdio.md
MDX makes it easy to add some simple tests.
=> Add basic tests using MDX

README.md, lib/index.mld, lib/picos_htbl/picos_htbl.ml, lib/picos_htbl/picos_htbl.mli, lib/picos_lwt/picos_lwt.mli, lib/picos_randos/dune, lib/picos_randos/picos_randos.ml, lib/picos_randos/picos_randos.mli, lib/picos_randos/select.none.ml, lib/picos_randos/select.some.ml, lib/picos_structured/run.ml, test/dune, test/test_scheduler.ocaml4.ml, test/test_scheduler.ocaml5.ml, test/test_server_and_client.ml, test/test_structured.ml
This introduces a randomized scheduler intended for testing.  This seems to be quite effective for finding bugs related to cases where code implicitly depends on scheduling.  It already revealed bugs during development.
=> Add `Picos_randos` — a randomized scheduler

lib/picos_randos/picos_randos.ml
My initial implementation left some unnecessary allocations in the effect handlers of `Picos_randos`.  Getting rid of them and checking with benchmarks whether the difference is noticeable.
...And looking at the benchmarks, it seems the performance difference is not noticeable (at least with the current benchmarks).  I recall that similar optimization with the `Picos_fifos` scheduler was noticeable, but most operations are significantly faster on that scheduler.  I'll merge the optimized version of `Picos_randos` anyway.
If you make everything slow enough, no individual small optimization seems worth it.
=> Avoid allocations in `Picos_randos`

lib/picos_htbl/picos_htbl.ml
This could improve write performance.
It seems this gives a barely measurable performance improvement in case of write heavy uncontended workloads.  That is one of the cases where this hash table performs _relatively_ worse than e.g. the Stdlib `Hashtbl` &mdash; so, although the improvement is barely measurable, I'll take it.
=> Make hash table write ops more optimistic

lib/picos_htbl/picos_htbl.ml
This avoids some code duplication/bloat in the implementation of the operations (grow/split, shrink/merge, copy) over a whole hash table.
=> Refactor to avoid code bloat in hash table

bench/bench_stdio.ml
This mirrors [change in a similar benchmark in multicore-bench](https://github.com/ocaml-multicore/multicore-bench/pull/21).
=> Perform `Picos_stdio.Unix` bench using multiple smaller blocks

bench.Dockerfile, bench/bench_binaries.ml, bench/dune, bench/main.ml, dune-project, picos.opam
This is useful for avoiding code bloat.
=> Add bench of binary sizes

lib/picos_htbl/picos_htbl.ml
See: https://github.com/ocaml-multicore/multicore-magic/issues/12
By getting the index at `create` the `Domain.at_exit` cleanup is hopefully registered early enough.
=> Get `instantaneous_domain_index` at `create` to schedule `at_exit`

lib/picos_mpscq/picos_mpscq.ml
When moving elements from the tail of the queue to the head, if there is more than one element on the tail, then leave the topmost (last pushed) element on the tail and don't update the tail pointer.  This reduces contention between producers and the consumer.
=> Try to avoid contention on back of the queue

lib/picos_structured/picos_structured.mli, lib/picos_structured/promise.ml, test/dune, test/test_lwt_unix.ml
Also avoid use of raw Picos API in tests.
=> Add `Promise.terminate_after`

lib/picos_structured/finally.ml
This moves allocations to the same block (so the compiler can merge them), reduces total allocations by one word, and avoids an unnecessary `Atomic.set`.
=> Tweak `Finally.(let^)` for performance

test/stm_run/util.ml
Thanks to @lyrm for reminding about the seeds!
=> Set random seed for each QCheck STM round

lib/picos_finally/picos_finally.ml
Changes:
- Always `Trigger.signal` after transfer/release has completed.  This just makes sense.
- Capture stack trace in handlers explicitly before calling user given code. This has the downside that capturing a stack trace allocates, which is both expensive and, I assume, also allows an asynchronous exception.  OTOH, in most cases it is likely better to ensure stack traces are captured properly.
- Establish handler before call of`Trigger.signal`.  As specified in the documentation, `Trigger.signal` should not raise, but it is perhaps better not to trust this.
=> Edge case adjustments

lib/picos_fifos/picos_fifos.ml
`Fiber.current ()` can be very performance critical. So, it is perhaps better not to make it any more expensive than necessary.
=> Don't reduce remaining quota in `current`

lib/picos_stdio_cohttp/picos_stdio_cohttp.ml
I noticed that when using the bytecode interpreter the request/response body was not always properly transmitted &mdash; a test will appear in a separate PR #222.  This simplifies the client to not try to write things concurrently and changes both sides to shutdown the connection partially after being done with writing or reading.  This seems to have eliminated the issue.
=> Fix to fully transmit body

lib/picos_fifos/picos_fifos.mli, lib/picos_randos/picos_randos.mli, lib/picos_threaded/picos_threaded.mli
=> Note about need to `Picos_select.configure` with multiple threads

bench/bench_fls_excluding_current.ml, lib/picos/bootstrap/picos_bootstrap.ml, lib/picos/picos.mli, lib/picos_structured/bundle.ml, test/test_picos.ml
This PR simplifies the `FLS` interface similarly to what was done for `TLS` (see #236).
=> Simplify FLS interface

lib/picos_select/dune, lib/picos_select/picos_select.ml, lib/picos_select/picos_select.mli
See https://github.com/ocaml-multicore/multicore-magic/issues/12
=> Ensure `instantaneous_domain_index`

lib/picos_multififos/picos_multififos.ml, lib/picos_randos/picos_randos.ml
While porting Kcas to Picos I replaced uses of domains with fibers spawned into a multithreaded scheduler and noticed that they didn't always manage to use all threads.
=> Fix to really try to use all threads

test/test_scheduler.ocaml5.ml
The quota is selected from the range [1, 100]:
- A quota of 1 is an edge case worth testing.
- A quota of 100 is high enough that fibers are unlikely to encounter it during most tests.
This also changes the test scheduler to print details on the scheduler in case the `main` raises.
=> Use a quota when running tests with FIFO schedulers

lib/picos_multififos/picos_multififos.ml, lib/picos_randos/picos_randos.ml
See:
- https://github.com/ocaml/ocaml/issues/12362
- https://github.com/ocaml/ocaml/issues/12363
=> Work around `Domain.spawn + Domain.join` not keeping stack traces

lib/picos_mux.multififo/picos_mux_multififo.ml, lib/picos_mux.random/picos_mux_random.ml
This tweaks the protocol for waking up worker threads in the multififo and random schedulers to make it less likely that a thread would go unused when there are ready fibers.  I don't have the mental energy at this moment to go through the logic carefully enough to satisfy myself on whether the changes are sufficient to provide an absolute guarantee that no thread goes unused.  I'm testing this in [Kcas PR that changes Kcas to use Picos](https://github.com/ocaml-multicore/kcas/pull/204) and it now seems to work. 🤞
=> Try even harder to use all threads when there are ready fibers

lib/picos_io/picos_io.ml
=> Also retry socketpair on `EACCES`

bench/bench_memory.ml, bench/bench_stubs.c, bench/dune
This also changes the label to emphasize that this include both stack and heap.
=> Include stack usage in memory usage benchmark

lib/picos_std.structured/bundle.ml
The native OCaml compiler allocates the stack space it needs at the entry to a function.  The native compiler is not able to properly reuse words it has allocated from stack based on liveness.  By breaking the continuations into separate functions one can "help" the native compiler as it then gets a chance to reallocate stack space at the entry to a new function.
=> Tweak to reduce stack usage of structured fibers

lib/picos_std.structured/picos_std_structured.mli
And also explain the reason behind this design choice within the sample library.
=> Note that canceling a promise does await for the fiber

lib/picos_std.structured/bundle.ml
The lifetime of bindings referenced by a closure in OCaml may be incorrectly extended as a reference to the closure record is kept alive for too long.
These changes work around that compiler bug by calling a non-inlined function at the start of the closure, which forces the compiler to generate code to extract all the bindings from the closure record and turn them into ordinary bindings.
=> Plug compiler generated space leaks in `Bundle`

lib/picos/trigger.bootstrap.ml
Trigger operations do not need to be recursive.
=> Minor performance tweaks

lib/picos/picos.ocaml5.ml
This moves the conversion of completed state to an option to a non-inlined function, which allows the usually vastly more common case to be inlined.
=> Another performance tweak

dune-project, picos.opam, picos_aux.opam, picos_io.opam, picos_mux.opam, picos_std.opam
Also, upgrade dependency on `backoff` from 0.1.0 to 0.1.1.
=> Fix `picos_std` package to depend on `picos_aux`

lib/picos_aux.htbl/picos_aux_htbl.ml
Using a mutable field should guarantee `Resize { ... }` allocates a new unique block that remains unique.
=> Use `mutable` to guarantee a new `Resize _` is allocated

example/guards.ml, test/dune, test/lib/test_scheduler/test_scheduler.ocaml4.ml, test/lib/test_scheduler/test_scheduler.ocaml5.ml, test/test_schedulers.ml
This PR adds a very basic test of fairness of a scheduler.
=> Add `?verbose` flag to test scheduler and add a test of fairness

lib/picos_io.select/picos_io_select.ml
This resets the wakeup state machine only after draining the pipe which can avoid a state transition in case a wakeup is called before clearing the state and allow select to be entered sooner.
=> Tweak select wakeup logic

bench/bench_bounded_q.ml
This should help to avoid the thundering herd problem and improve thruput.
=> Avoid `broadcast` in `Bounded_q` benchmark
